In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
# create numpy array
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [4]:
np.__version__

'1.21.1'

In [5]:
type(arr1)

numpy.ndarray

In [6]:
#0d Array
ZeroArray=np.array(20)
print(ZeroArray)
print(type(ZeroArray))
print(ZeroArray.shape)

20
<class 'numpy.ndarray'>
()


In [7]:
# 1d Array
oneArray=np.array([1,2,3,4,5])
print(oneArray)
print(type(oneArray))
print(oneArray.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
# 2d array
twoArray=np.array([[1,2,3],[4,5,6]])
print(twoArray)
print(type(twoArray))
print(twoArray.shape)
print(twoArray.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
int32


In [9]:
#3d array
ThreeArray=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(ThreeArray)
print(type(ThreeArray))
print(ThreeArray.shape)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
(2, 2, 3)


In [10]:
# check dimension
a=np.array(20)
b=np.array([[1,2,3],[4,5,6]])
c=np.array([1,2,3,4,5])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
2
1
3


In [11]:
# indexing
#1d 
oneArray[0]

1

In [12]:
oneArray[-1]

5

In [13]:
print(twoArray)


[[1 2 3]
 [4 5 6]]


In [14]:
print(twoArray[0][1])

2


In [15]:
print(ThreeArray)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [16]:
print(ThreeArray[0][1][2])

6


In [17]:
#slicing
print(oneArray)


[1 2 3 4 5]


In [18]:
print(oneArray[1:4])

[2 3 4]


In [19]:
print(oneArray[1:])

[2 3 4 5]


In [20]:
print(oneArray.dtype)

int32


In [21]:
data=np.array(["a","b","c","d"])
data.dtype

dtype('<U1')

In [22]:
# create array with data type
num=np.array([1,2,3,4],dtype='i')
print(num)
print(num.dtype)

[1 2 3 4]
int32


In [23]:
# astype to chnage data type
num=num.astype('f')
print(num)
print(num.dtype)

[1. 2. 3. 4.]
float32


In [24]:
num=num.astype('S')
print(num)
print(num.dtype)

[b'1.0' b'2.0' b'3.0' b'4.0']
|S32


In [25]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [26]:
np.zeros((2,3),dtype=np.int16,order='C')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [27]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [28]:
np.ones((2,2),dtype=np.int16)

array([[1, 1],
       [1, 1]], dtype=int16)

In [29]:
e=np.array([(1,2,3),(4,5,6),(8,9,10)])
e

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [30]:
# reshape
np.reshape(e,(3,3),order='F')

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [31]:
# flatten
e.flatten()

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10])

In [32]:
# hstack
a=np.array([1,2,3])
b=np.array([8,9,7])
c=np.hstack((a,b))
print(c)
print(c.shape)

[1 2 3 8 9 7]
(6,)


In [33]:
# Vstack
a=np.array([1,2,3])
b=np.array([8,9,7])
c=np.vstack((a,b))
print(c)
print(c.shape)

[[1 2 3]
 [8 9 7]]
(2, 3)


In [34]:
np.random.normal(8,0.2,5)

array([7.79035104, 7.78200022, 8.07071992, 7.89239254, 7.88149322])

In [35]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [37]:
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [38]:
np.linspace(1,5,num=10,endpoint=False)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

In [39]:
np.logspace(1,5,num=10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [40]:
np.logspace(1,5,num=10,endpoint=False)

array([1.00000000e+01, 2.51188643e+01, 6.30957344e+01, 1.58489319e+02,
       3.98107171e+02, 1.00000000e+03, 2.51188643e+03, 6.30957344e+03,
       1.58489319e+04, 3.98107171e+04])

In [41]:
arr=np.arange(100,110)
arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [42]:
print("Min:",arr.min())
print("Max:",arr.max())
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("standard Deviation:",arr.std())

Min: 100
Max: 109
Mean: 104.5
Median: 104.5
standard Deviation: 2.8722813232690143


In [43]:
print(a)
print(b)

[1 2 3]
[8 9 7]


In [44]:
np.dot(a,b)

47